Spec tests for Tic-Tac-Toe
SajjadAhmad14/ruby-tic-tac-toe-game pull request #1
Opened 2020-09-16 13:04 UTC by SajjadAhmad14

- Wrote specs for #update_board
- Wrote specs for #print_board
- Wrote specs for #create_line_in_board
- Wrote specs for #blank?
- Wrote specs for #who_won?

2020-09-16 14:18 UTC, bertil291utn commented
- [ ] Edit pull request message following this [guideline](https://cdn.filestackcontent.com/osvFJEkQHWQsgDe0PJoQ)
- [ ] Elaborate run test section. Follow this [example](https://github.com/Bekhzod96/tic_tac_toe#run)
- [ ] Add n anther file to test only player test
Example: 
```ruby
define Player do 
  # Add a test to check if the object was created 
end
```

2020-09-16 14:27 UTC, bertil291utn requested changes
# **Status:** Changes requested 🟠 
<p align="center"> <img src="https://i.cubeupload.com/4HbSFK.jpg" alt="image" width="60" /> <br><strong>Not yet</strong> </p>

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to accomplish with all requirements, you required to do these changes, listed below:
- [ ] Edit pull request message following this [guideline](https://cdn.filestackcontent.com/osvFJEkQHWQsgDe0PJoQ)
- [ ] Elaborate run test section. Follow this [example](https://github.com/Bekhzod96/tic_tac_toe#run)
- [ ] Add in another file to test only player test
Example: 
```ruby
define Player do 
  # Add a test to check if the object was created 
end
```
- All the public methods of the classes implemented in project OOP are tested ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/all_tic_tac_toe.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))
  - [ ] Add to test this method `def move(player)`
### Summary
- Split up in a different file for board class
- Also, test player class
-  Don't forget to work with inline comments below this comment box.

***

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-09-16 14:27 UTC, bertil291utn commented on spec/game_spec.rb
> +end
## Split it up another file to avoid confusion
- [ ] Add in another  file called `board_rspec.rb`, it's good practice to split it into different files according to each class

2020-09-17 09:07 UTC, SajjadAhmad14 commented on spec/game_spec.rb
> +end
#move of Game class could not be tested because it contains a class Method of Main. When I try to initialize that in my spec file it starts running the game actually.

2020-09-17 10:58 UTC, maelfosso approved these changes
# Congratulations :clap: 

Thank you for applying the suggested changes. 
You can merge it now :+1: 

Good continuation :handshake: 

Mael FOSSO

2020-09-17 11:39 UTC, merged